import { Montserrat } from 'next/font/google';
import './globals.css';
import ReduxProvider from '@/store/ReduxProvider';
import FavoriteTracksSync from '@/components/FavoriteTracksSync/FavotiteTracksSync';

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'], // добавь cyrillic, если нужна кириллица!
  weight: ['400', '500', '600', '800', '700'], // укажи нужные начертания
  display: 'swap', // рекомендуется для плавной загрузки
});
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <FavoriteTracksSync />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
