// app/layout.tsx (или app/layout.jsx, если без TS)
import './globals.css';
import MainNav from '../components/MainNavigation/MainNav';
import SideBar from '../components/SideBar/SideBar';
import Bar from '../components/Bar/Bar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="wrapper">
          <div className="app-content">
            <MainNav />
            <main className="main-content">{children}</main>
            <SideBar />
          </div>
          <Bar />
        </div>
      </body>
    </html>
  );
}
